---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rainbow
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/rainbow/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: rainbow
