apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orange
  name: orange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orange
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orange
        group: rainbow
    spec:
      containers:
      - image: jpetazzo/color
        name: color
