---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dockercoins-helm
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/dockercoins-helm/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dockercoins-helm
