---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worker
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  releaseName: worker
  targetNamespace: dockercoins-helm
  values:
    livenessProbe: null
    readinessProbe: null
    service: false
