apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../apps/dockercoins-yaml/gotk.yaml
- ../../../apps/dockercoins-helm/gotk.yaml
- ../../../apps/rainbow/gotk.yaml
- ../../../apps/kube-prometheus-stack/flux.yaml
- ../../../apps/myapp/flux.yaml
