---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m0s
  releaseName: redis
  targetNamespace: dockercoins-helm
  values:
    image:
      repository: redis
      tag: latest
    livenessProbe: null
    readinessProbe: null
    service:
      port: 6379
