---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webui
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  releaseName: webui
  targetNamespace: dockercoins-helm
  values:
    service:
      type: LoadBalancer
