---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dockercoins-umbrella
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/dockercoins
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: dockercoins-umbrella
